apiVersion: v1
kind: ConfigMap
metadata:
  name: ncert10-quiz-config
  namespace: ncert10-quiz
data:
  NODE_ENV: "production"
  PORT: "3000"
  AWS_REGION: "eu-north-1"
  DYNAMODB_TABLE_ATTEMPTS: "ncert10-quiz-dev-attempts"
  DYNAMODB_TABLE_LEADERBOARD: "ncert10-quiz-dev-leaderboard"
  LEADERBOARD_PATH: "/app/.data/leaderboard.json"
