apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "ncert10-quiz.fullname" . }}-config
  labels:
    {{- include "ncert10-quiz.labels" . | nindent 4 }}
data:
  NODE_ENV: {{ .Values.env.NODE_ENV | quote }}
  PORT: {{ .Values.env.PORT | quote }}
  NEXT_PUBLIC_APP_URL: {{ .Values.env.NEXT_PUBLIC_APP_URL | quote }}
  LEADERBOARD_PATH: {{ .Values.env.LEADERBOARD_PATH | quote }}
