apiVersion: v1
kind: Service
metadata:
  name: {{ include "ncert10-quiz.fullname" . }}
  labels:
    {{- include "ncert10-quiz.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "ncert10-quiz.selectorLabels" . | nindent 4 }}
